# main.py

STARTWINDOWWIDTH: int = 800
STARTWINDOWHEIGHT: int = 600

DEFAULTBALLRADIUS: int = 30
DEFAULTGRAVITY: int = 1500
DEFAULTFRICTION: float = 0.08
DEFAULTBOUNCE: float = 0.8

MAXPREVIEWSIZERATIO: float = 0.25

DEFAULTTARGETFPS: int = 60

# ball.py

G = 3e5
GRAVITYEPSILON = 100

RADIALDAMPINGCOEFFICIENT: float = 3.0
TANGENTIALDAMPINGCOEFFICIENT: float = 0.3

SLIDINGFRICTIONRATIO: float = 0.1

MOMENTUMARROWCONSTANT: float = 0.06
GRAVITYARROWCONSTANT: float = 0.03
NORMALARROWCONSTANT: float = 0.03
FRICTIONARROWCONSTANT: float = 0.07